// Nebula ↔ Pi bridge — AUTO-GENERATED by Nebula, do not edit.
import { spawn } from "node:child_process";
import { basename } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

function sessionIdFor(ctx: any): string {
  try {
    const direct = ctx?.sessionManager?.getSessionId?.();
    if (direct) return String(direct);
    const file = ctx?.sessionManager?.getSessionFile?.();
    if (file) return basename(String(file)).replace(/\.jsonl$/, "");
  } catch (_) {}
  return `pid-${process.pid}`;
}

export default function (pi: ExtensionAPI) {
  let active = false;
  let sequence = 0;
  const sequenceEpoch = BigInt(Date.now()) * 1000000n;
  const send = (kind: "session-start" | "prompt" | "tool-complete" | "done" | "session-end", ctx?: any) => {
    const hook = process.env.NEBULA_HOOK_EXE;
    if (!hook) return;
    try {
      const session_id = sessionIdFor(ctx);
      const bridge_sequence = (sequenceEpoch + BigInt(++sequence)).toString();
      const event_id = `${session_id}:pid-${process.pid}:${bridge_sequence}`;
      spawn(hook, ["pi", JSON.stringify({
        kind,
        session_id,
        bridge_sequence,
        event_id,
        cwd: ctx?.cwd || "",
      })], {
        detached: true,
        stdio: "ignore",
        windowsHide: true,
      }).unref();
    } catch (_) {}
  };

  pi.on("agent_start", async (_event, ctx) => {
    active = true;
    send("prompt", ctx);
  });
  pi.on("agent_end", async (_event, ctx) => {
    if (!active) return;
    active = false;
    send("done", ctx);
  });
  try { pi.on("session_start", async (_event, ctx) => send("session-start", ctx)); } catch (_) {}
  try { pi.on("tool_result", async (_event, ctx) => send("tool-complete", ctx)); } catch (_) {}
  try { pi.on("session_shutdown", async (_event, ctx) => send("session-end", ctx)); } catch (_) {}
}
